use_frameworks!

platform :ios, '8.0'

target 'InnotechIMProtocol_Example' do
  pod 'InnotechIMProtocol', :path => '../'

  target 'InnotechIMProtocol_Tests' do
    inherit! :search_paths

    
  end
end
